---
name: Genmon
version: a45a9eb58ca6ef1f2348103175d0d94086c1f67e
description: "Genmon addon for Hassio"
url: "https://github.com/davidflypei/genmon-addon"
slug: "genmon"
stage: "experimental"
startup: "application"
boot: "auto"
arch:
  - amd64
  - armhf
map:
  - config:rw
ingress: true
ingress_port: 8000
image: "ghcr.io/alexyao2015/genmon-addon"
