---
name: Genmon
version: 1.0.0
slug: genmon
panel_icon: mdi:gauge
description: Genmon addon for Hassio
startup: application
boot: auto
map:
  - config:rw
url: https://github.com/davidflypei/genmon-addon
uart: true
udev: true
usb: true
host_network: false
hassio_api: true
stage: experimental
arch:
  - amd64
  - i386
  - armv7
  - armhf
  - aarch64
ingress: true
ingress_port: 8000
