---
name: Genmon
version: a45a9eb58ca6ef1f2348103175d0d94086c1f67e
slug: genmon
panel_icon: mdi:gauge
description: Genmon addon for Hassio
startup: application
boot: auto
map:
  - config:rw
url: https://github.com/davidflypei/genmon-addon
uart: true
udev: true
usb: true
host_network: false
hassio_api: true
stage: experimental
arch:
  - amd64
  - i386
  - armv7
  - armhf
  - aarch64
image: ghcr.io/alexyao2015/genmon-addon